@startuml
title Cadastro do Licenciado
actor Integrador
participant "Sso" as Sso
participant "Api do Integrador" as ApiIntegrador

group 1. Obter Token de Autenticação
    Integrador -> Sso: Obtem o token de autenticação (Obter Token de Autenticação)
    Sso --> Integrador: Retorna o access token
end group

group 2. Registrar o Licenciado
    Integrador -> ApiIntegrador: Registra o licenciado (Registrar Licenciado)
    ApiIntegrador --> Integrador: Retorna o id do licenciado e senha provisória para o usuário master
end group
@enduml
